name: Run pgTAP Tests

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mgs122/postgres-pgtap:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run containers
        run: docker-compose up --build -d

      - name: Wait for containers to be ready
        run: docker-compose exec -T db pg_isready -U myuser -d mydatabase -h localhost -p 5432

      - name: Run pgTAP tests
        run: docker-compose run --rm --entrypoint='bash -c "cd /app && PGPASSWORD=mypassword pg_prove --host db --username myuser --dbname mydatabase --ext .sql -r tests/"' myapp

      - name: Shutdown containers
        run: docker-compose down

      - name: Clean up dangling volumes
        run: docker volume prune --force

      - name: Finish
        run: echo "Tests completed successfully"
