name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 10  # Adjust sleep duration as needed to ensure services are ready

    - name: Run SQL script in PostgreSQL
      run: docker-compose exec -T db psql -U myuser -d mydatabase -f /docker-entrypoint-initdb.d/init-db.sql

    - name: Run tests
      run: docker-compose run --rm --entrypoint='bash -c "cd /pgtap && PGPASSWORD=mypassword pg_prove --host db --username myuser --dbname mydatabase --ext .sql -r tests/"' myapp

    - name: Tear down Docker Compose
      run: docker-compose down -v
